// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZoneRV.DBContexts;

#nullable disable

namespace ZoneRV.Migrations.Migrations
{
    [DbContext(typeof(ProductionContext))]
    [Migration("20250203231514_FixedDescriptions")]
    partial class FixedDescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("production")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZoneRV.Models.Location.LineLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("WorkspaceLocationId");

                    b.ToTable("LineLocation", "production");
                });

            modelBuilder.Entity("ZoneRV.Models.Location.LineLocationCustomName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("LineLocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Order")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("LineLocationId");

                    b.ToTable("LineLocationCustomName", "production");
                });

            modelBuilder.Entity("ZoneRV.Models.Location.LocationInventoryName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("LineLocationId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("LineLocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationInventoryName", "production");
                });

            modelBuilder.Entity("ZoneRV.Models.Location.WorkspaceLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceLocation", "production");
                });

            modelBuilder.Entity("ZoneRV.Models.Production.AreaOfOrigin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("AreaOfOrigin", "production");
                });

            modelBuilder.Entity("ZoneRV.Models.Production.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("Model", "production");
                });

            modelBuilder.Entity("ZoneRV.Models.Production.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Line", "production");
                });

            modelBuilder.Entity("ZoneRV.Models.Production.ProductionWorkspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Workspace", "production");
                });

            modelBuilder.Entity("ZoneRV.Models.Location.LineLocation", b =>
                {
                    b.HasOne("ZoneRV.Models.Production.ProductionLine", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZoneRV.Models.Location.WorkspaceLocation", "WorkspaceLocation")
                        .WithMany("LineLocations")
                        .HasForeignKey("WorkspaceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("WorkspaceLocation");
                });

            modelBuilder.Entity("ZoneRV.Models.Location.LineLocationCustomName", b =>
                {
                    b.HasOne("ZoneRV.Models.Location.LineLocation", "LineLocation")
                        .WithMany("CustomLocationNames")
                        .HasForeignKey("LineLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineLocation");
                });

            modelBuilder.Entity("ZoneRV.Models.Location.LocationInventoryName", b =>
                {
                    b.HasOne("ZoneRV.Models.Location.LineLocation", null)
                        .WithMany("InventoryLocations")
                        .HasForeignKey("LineLocationId");

                    b.HasOne("ZoneRV.Models.Location.WorkspaceLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ZoneRV.Models.Location.WorkspaceLocation", b =>
                {
                    b.HasOne("ZoneRV.Models.Production.ProductionWorkspace", "Workspace")
                        .WithMany("WorkspaceLocations")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ZoneRV.Models.Production.AreaOfOrigin", b =>
                {
                    b.HasOne("ZoneRV.Models.Production.ProductionLine", "Line")
                        .WithMany("AreaOfOrigins")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("ZoneRV.Models.Production.Model", b =>
                {
                    b.HasOne("ZoneRV.Models.Production.ProductionLine", "Line")
                        .WithMany("Models")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("ZoneRV.Models.Production.ProductionLine", b =>
                {
                    b.HasOne("ZoneRV.Models.Production.ProductionWorkspace", "Workspace")
                        .WithMany("Lines")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ZoneRV.Models.Location.LineLocation", b =>
                {
                    b.Navigation("CustomLocationNames");

                    b.Navigation("InventoryLocations");
                });

            modelBuilder.Entity("ZoneRV.Models.Location.WorkspaceLocation", b =>
                {
                    b.Navigation("LineLocations");
                });

            modelBuilder.Entity("ZoneRV.Models.Production.ProductionLine", b =>
                {
                    b.Navigation("AreaOfOrigins");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("ZoneRV.Models.Production.ProductionWorkspace", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("WorkspaceLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
